### ISSUE TITLE
Connect via SSH

### ISSUE THREAD

**Issue by mytototo** [Azure/terraform-azurerm-computegroup#3]
Hi,

I'm trying to use this Terraform module.

I have a question: how do I access the VM using SSH?
I tried to connect using the public IP address but it doesn't work. Any idea?

Thanks.

**Comment by dcaro** [comment]
The computegroup expose a set of port load balanced across all the VMs of the group. In order to ssh to each individual VM of the group, we recommend the approach of having a bastion host on the vnet.

**Comment by mytototo** [comment]
All right I understand.
Do you have any working example of this with this Terraform module ?

**Comment by dcaro** [comment]
Sorry for the delay @mytototo. I don't have an example right now but I will try to have one by Friday end of day. Thanks.

**Comment by mytototo** [comment]
All right, thanks a lot for your time and help @dcaro.

**Comment by mytototo** [comment]
@dcaro: do you have time to make a quick example with a bastion host like we discussed ? Thanks for your time.

**Comment by dcaro** [comment]
@mytototo, I have just pushed the sample in the [README](https://github.com/Azure/terraform-azurerm-computegroup/blob/jumpbox-example/README.md).
Can you have a look and let me know if this helps? Thanks.

**Comment by mytototo** [comment]
I just tried it. Looks like it works fine, thank you very much @dcaro.
Regarding the jumpbox, do you advise to set `disable_password_authentication` to `true` ?

**Comment by dcaro** [comment]
This is a more secure way to connect to the jumpbox, I recommend to keep this settings.

**Comment by mytototo** [comment]
All right, thanks again for your time and help @dcaro. I appreciate.
