### ISSUE TITLE
Error getting plugins: module root: module computegroup: cmd_extension is not a valid parameter

### ISSUE THREAD

**Issue by mashayev** [Azure/terraform-azurerm-computegroup#5]
Hey,

```
➜  terraform -v
Terraform v0.11.0
+ provider.azurerm v0.3.3
```

When using your examples in README the `terraform init` fails due to `cmd_extension is not a valid parameter`
When removing the `cmd_extension` from module "computegroup" init finish succesfully, 
but it still fails due to the network module(Not related to your module).

This is the issue for  network module https://github.com/Azure/terraform-azurerm-network/issues/4

**Comment by dcaro** [comment]
Hi @mashayev thanks for raising the issue. It looks like this is a versioning issue of the provider. The version on the repo is v1.1.0 and the registry has an older version (v1.0.1).
Let me try to get the registry updated.

**Comment by dcaro** [comment]
@mashayev the versioning issue has been resolved, can you verify and let me know if this works for you? Please ensure that you run the init command again you get the latest version of the module.

**Comment by dtzar** [comment]
Please let us know if this issue still exists at which time we can reopen the issue.
