### ISSUE TITLE
Replace Travis AZURE Secrets

### ISSUE THREAD

**Issue by dtzar** [Azure/terraform-azurerm-computegroup#9]
Currently, I have the `rake e2e` Travis setup to use my personal MSFT credentials (in secure ENV variables) and this should be replaced with the engineering team's Azure credentials.

**Comment by dcaro** [comment]
@metacpp can you have a look at this ? Thanks.

**Comment by metacpp** [comment]
@dcaro @dtzar I have replaced the secrets with our team's sub.
